version: '3.8'
services: 
  db: 
    image: postgres:15.6
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.14
    restart: always
    ports: 
      - "6379:6379"

volumes:
  postgres-data: